#!/usr/bin/env node

/**
 * generate-latex.mjs — Validate and compile a generated .tex CV file to PDF
 *
 * Usage:
 *   node generate-latex.mjs <input.tex> [output.pdf]
 *
 * Reads the .tex file, validates structure, compiles to PDF via tectonic or pdflatex.
 * If output.pdf is omitted, writes to the same directory as input with .pdf extension.
 * The .tex file is generated by the AI agent using templates/cv-template.tex.
 *
 * Requires: tectonic (preferred, brew install tectonic) or pdflatex (MiKTeX / TeX Live) on PATH.
 */

import { readFile, writeFile, stat, copyFile, rm } from 'fs/promises';
import { resolve, basename, dirname, join } from 'path';
import { execFileSync } from 'child_process';
import { existsSync, mkdirSync } from 'fs';

const REQUIRED_SECTIONS = [
  '\\\\section{Education}',
  '\\\\section{Work Experience}',
  '\\\\section{Personal Projects}',
  '\\\\section{Technical Skills}',
];

const REQUIRED_COMMANDS = [
  '\\\\resumeSubheading',
  '\\\\resumeItem',
  '\\\\resumeProjectHeading',
];

async function main() {
  // --byo (bring-your-own-template): the input .tex is the user's own resume,
  // not the bundled templates/cv-template.tex. Skip the structural validation
  // that assumes the bundled macros/section names; just sanity-check + compile.
  const args = process.argv.slice(2);
  const byo = args.includes('--byo');
  const positional = args.filter(a => a !== '--byo');
  const inputPath = positional[0];
  const outputPath = positional[1]; // optional
  if (!inputPath) {
    console.error('Usage: node generate-latex.mjs [--byo] <input.tex> [output.pdf]');
    process.exit(1);
  }

  const absPath = resolve(inputPath);
  let content;
  try {
    content = await readFile(absPath, 'utf-8');
  } catch (err) {
    console.error(`Error reading ${absPath}: ${err.message}`);
    process.exit(1);
  }

  const issues = [];

  // Structural checks for the bundled template only. In --byo mode the user
  // supplies their own document class, macros, and section names, so these
  // would produce false negatives — skip them and rely on tectonic to catch
  // real LaTeX errors at compile time.
  if (!byo) {
    // Check required sections
    for (const pattern of REQUIRED_SECTIONS) {
      if (!new RegExp(pattern).test(content)) {
        issues.push(`Missing section matching: ${pattern}`);
      }
    }

    // Check required commands are used
    for (const cmd of REQUIRED_COMMANDS) {
      if (!new RegExp(cmd).test(content)) {
        issues.push(`Missing command: ${cmd}`);
      }
    }
  }

  // Check document structure (applies to both modes)
  if (!content.includes('\\begin{document}')) {
    issues.push('Missing \\begin{document}');
  }
  if (!content.includes('\\end{document}')) {
    issues.push('Missing \\end{document}');
  }

  // Check for unresolved placeholders (applies to both modes — catches a
  // tailoring step that left a {{TOKEN}} unfilled)
  const unresolvedMatch = content.match(/\{\{[A-Z_]+\}\}/g);
  if (unresolvedMatch) {
    issues.push(`Unresolved placeholders: ${[...new Set(unresolvedMatch)].join(', ')}`);
  }

  // \location is used by some BYO templates but commonly left commented out;
  // catch the "used but never defined" case before it becomes a cryptic
  // "Undefined control sequence" at compile time.
  if (byo && /(^|[^%].*)\\location\b/m.test(content) &&
      !/^\s*[^%]*\\def\\location\b/m.test(content) &&
      !/^\s*[^%]*\\newcommand\{?\\location\}?/m.test(content)) {
    issues.push('\\location is used but never defined (uncommented). The tailoring step must write an active \\def\\location{City, Region} before \\begin{document}.');
  }

  // Check for common unescaped special chars in text (heuristic)
  const lines = content.split('\n');
  let resumeItemCount = 0;
  let subheadingCount = 0;
  let projectHeadingCount = 0;

  for (const line of lines) {
    if (/\\resumeItem\{/.test(line)) resumeItemCount++;
    if (/\\resumeSubheading[^C]/.test(line)) subheadingCount++;
    if (/\\resumeProjectHeading/.test(line)) projectHeadingCount++;
  }

  // Check pdfgentounicode (bundled template only — BYO templates may use a
  // different ATS-compatibility approach, e.g. lmodern + T1 fontenc)
  if (!byo && !content.includes('\\pdfgentounicode=1')) {
    issues.push('Missing \\pdfgentounicode=1 (ATS compatibility)');
  }

  const fileInfo = await stat(absPath);
  const sizeKB = (fileInfo.size / 1024).toFixed(1);

  // Output report as JSON
  const report = {
    file: basename(absPath),
    path: absPath,
    sizeKB: parseFloat(sizeKB),
    counts: {
      resumeItems: resumeItemCount,
      subheadings: subheadingCount,
      projectHeadings: projectHeadingCount,
    },
    issues,
    valid: issues.length === 0,
  };

  // If validation fails, report and exit
  if (issues.length > 0) {
    console.log(JSON.stringify(report, null, 2));
    process.exit(1);
  }

  // --- Compile .tex → .pdf ---
  const texDir = dirname(absPath);
  const texBase = basename(absPath, '.tex');
  const defaultPdf = join(texDir, `${texBase}.pdf`);
  const targetPdf = outputPath ? resolve(outputPath) : defaultPdf;

  // Ensure output directory exists
  const targetDir = dirname(targetPdf);
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }

  // Detect available engine: prefer tectonic, fall back to pdflatex
  let engine = null;
  for (const candidate of ['tectonic', 'pdflatex']) {
    try {
      execFileSync(candidate, ['--version'], { stdio: 'pipe' });
      engine = candidate;
      break;
    } catch { /* not found */ }
  }

  if (!engine) {
    report.compiled = false;
    report.compileError = 'No LaTeX engine found. Install tectonic (brew install tectonic) or pdflatex.';
    console.log(JSON.stringify(report, null, 2));
    process.exit(1);
  }

  report.engine = engine;

  // Build a normalized compile copy (used for BOTH engines).
  //
  // 1) Unicode normalization — mirrors generate-pdf.mjs (the HTML path). A literal
  //    em dash (U+2014) is silently DROPPED under tectonic's XeTeX engine, merging
  //    the surrounding words ("Amazon S3—enabling" -> "Amazon S3enabling"). Smart
  //    quotes/ellipsis are likewise unreliable and read as AI-generated. Convert to
  //    ASCII/TeX equivalents so output renders correctly and is ATS-clean. (Authors
  //    should avoid em dashes in the first place — see modes/_shared.md — this is the
  //    safety net.)
  // 2) tectonic only — strip pdflatex-only primitives/packages that crash XeTeX.
  const normalizeUnicode = (s) => s
    .replace(/—/g, '-')            // em dash  -> hyphen (matches generate-pdf.mjs)
    .replace(/–/g, '-')            // en dash  -> hyphen
    .replace(/[‘’]/g, "'")    // smart single quotes -> straight
    .replace(/[“”]/g, "''")   // smart double quotes -> straight (TeX)
    .replace(/…/g, '...')          // ellipsis -> three dots
    .replace(/ /g, '~');           // non-breaking space -> TeX tie

  const dashHits = (content.match(/[—–]/g) || []).length;
  if (dashHits) report.unicodeNormalized = { dashes: dashHits };

  let compileSource = normalizeUnicode(content);
  if (engine === 'tectonic') {
    compileSource = compileSource
      .replace(/\\pdfgentounicode\s*=\s*\d+[^\n]*\n?/g, '')
      .replace(/\\input\{glyphtounicode\}[^\n]*\n?/g, '')
      // pdfx (PDF/A) fails under XeTeX: "CreationDate is not properly supported".
      // The text layer stays ATS-readable without it; for true PDF/A, compile
      // with pdflatex (e.g. on Overleaf).
      .replace(/\\usepackage(\[[^\]]*\])?\{pdfx\}[^\n]*\n?/g, '% pdfx stripped for tectonic/XeTeX build\n');
  }
  const compilePath = join(texDir, `${texBase}._compile.tex`);
  await writeFile(compilePath, compileSource, 'utf-8');

  try {
    if (engine === 'tectonic') {
      // Tectonic handles multi-pass automatically; --outdir sets output location
      execFileSync('tectonic', ['--outdir', texDir, compilePath], {
        cwd: texDir,
        stdio: 'pipe',
        timeout: 120_000,
      });
    } else {
      const pdflatexArgs = [
        '-no-shell-escape',
        '-interaction=nonstopmode',
        '-halt-on-error',
        `-output-directory=${texDir}`,
        compilePath,
      ];
      // First pass
      execFileSync('pdflatex', pdflatexArgs, { cwd: texDir, stdio: 'pipe', timeout: 120_000 });
      // Second pass (resolves referenceS))
      execFileSync('pdflatex', pdflatexArgs, { cwd: texDir, stdio: 'pipe', timeout: 120_000 });
    }

    report.compiled = true;
  } catch (err) {
    const logPath = join(texDir, `${texBase}.log`);
    let latexError = err.message;
    try {
      const log = await readFile(logPath, 'utf-8');
      const errorLines = log.split('\n').filter(l => l.startsWith('!'));
      if (errorLines.length > 0) {
        latexError = errorLines.join('\n');
      }
    } catch { /* no log file */ }

    report.compiled = false;
    report.compileError = latexError;
  }

  // Post-compile: move PDF and clean up (separate from compile errors)
  if (report.compiled) {
    // PDF is named after the normalized temp compile file (both engines)
    const compileBase = basename(compilePath, '.tex');
    const compiledPdf = join(texDir, `${compileBase}.pdf`);

    try {
      await copyFile(compiledPdf, targetPdf);
      if (resolve(compiledPdf) !== resolve(targetPdf)) {
        await rm(compiledPdf).catch(() => {});
      }

      const pdfStat = await stat(targetPdf);
      report.pdf = {
        path: targetPdf,
        sizeKB: parseFloat((pdfStat.size / 1024).toFixed(1)),
      };
    } catch (err) {
      report.postCompileError = `Failed to finalize PDF: ${err.message}`;
    }

    // Clean up auxiliary files and tectonic temp .tex (best-effort)
    const auxExts = ['.aux', '.log', '.out', '.fls', '.fdb_latexmk', '.synctex.gz'];
    for (const ext of auxExts) {
      await rm(join(texDir, `${compileBase}${ext}`)).catch(() => {});
    }
    // Remove the normalized temp compile file (both engines)
    await rm(compilePath).catch(() => {});
  }

  console.log(JSON.stringify(report, null, 2));
  process.exit(report.compiled ? 0 : 1);
}

main();
